import Head from "next/head";
import react, { useState } from "react";
import Image from "next/image";
import ClearData from "../compononets/cleardata";
import Heading from "../compononets/heading";
import Navbar from "../compononets/navbar";
import TextArea from "../compononets/textarea";

export default function Home() {
  const [content, setContent] = useState("");
  return (
    <div>
      <Head>
        <title>Online Note Taking Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar content={content} />
      <Heading />
      <TextArea content={content} setContent={setContent} />
    </div>
  );
}
