import Head from "next/head";
import react, { useState } from "react";
import Heading from "../compononets/heading";
import Navbar from "../compononets/navbar";
import TextArea from "../compononets/textarea";

export default function Home() {
  const [content, setContent] = useState("");
  return (
    <div>
      <Head>
        <title>Online Note Taking Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="title" content="Online Note Taking Next App" />
                <meta
                    name="description"
                    content="Keep track of your document's word count!"
                />

                <meta property="og:type" content="website" />
                <meta property="og:url" content="/" />
                <meta property="og:title" content="Online Note Taking Next App" />
                <meta
                    property="og:description"
                    content="Keep track of your document's with text summart and download locally or save on Browser."
                />
                <meta property="og:image" content={process.env.NEXT_PUBLIC_META_IMG} />

                <meta property="twitter:card" content="summary_large_image" />
                <meta property="twitter:url" content="/" />
                <meta property="twitter:title" content="Online Note Taking Next App" />
                <meta
                    property="twitter:description"
                    content="Keep track of your document's with text summart and download locally or save on Browser."
                />
                <meta
                    property="twitter:image"
                    content={process.env.NEXT_PUBLIC_META_IMG}
                />
      </Head>
      <Navbar content={content} />
      <Heading />
      <TextArea content={content} setContent={setContent} />
    </div>
  );
}
